"""add blacklist table

Revision ID: 164d5e72f949
Revises: c943b7194320
Create Date: 2019-11-11 15:27:44.632013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164d5e72f949'
down_revision = 'c943b7194320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
